# This is a basic workflow to help you get started with Actions

name: CI

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.1
        with:
          arguments: -p="./" --ignore="**/.vscode/**, **/*.env, **/.mypy_cache/**, **/tests/**"
          
name: CD
- name: Docker ECR
  # You may pin to the exact commit or the version.
  # uses: appleboy/docker-ecr-action@174bc7ab545bf5c4f4492240c4d839a987643559
  uses: appleboy/docker-ecr-action@v0.0.3
  with:
    # amazon access key
    access_key: # optional
    # amazon secret access key
    secret_key: # optional
    # docker registry
    registry: # optional
    # amazon region, defaults to us-east-1
    region: # optional, default is us-east-1
    # repository name for the image
    repo: # optional
    # filename of ecr lifecycle json policy
    lifecycle_policy: # optional
    # filename of ecr repository json policy
    repository_policy: # optional
    # repository tag for the image, defaults to latest
    tags: # optional, default is latest
    # dockerfile to be used, defaults to Dockerfile
    dockerfile: # optional, default is Dockerfile
    # auth token for the registry
    auth: # optional
    # the context path to use, defaults to root of the git repo
    context: # optional, default is .
    # replace existing matched image tags
    force_tag: # optional
    # enable insecure communication to this registry
    insecure: # optional
    # use a mirror registry instead of pulling images directly from the central Hub
    mirror: # optional
    # use for pass bridge ip
    bip: # optional
    # set custom dns servers for the container
    custom_dns: # optional
    # supports aufs, overlay or vfs drivers
    storage_driver: # optional
    # images to consider as cache sources
    cache_from: # optional
    # default build tags
    auto_tag: # optional
    
